Feedback/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.shortcuts import render
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from User.views import signup, user_login, user_logout, verification
from Student.views import student_view, student_requested_courses_view, archiveCourseStudent_view
from Professor.views import professor_view,archiveCourseProfessor_view,professorDeleteCourse_view, professorArchiveCourse_view, professor_notifications, prof_add_student, prof_reject_student, verify_all

from . import settings
from Course.views import *
from Question.views import *

def home_view(request):
    return render(request, "index.html", {})



urlpatterns = [
    path('', user_login, name='home'),
    path('admin/', admin.site.urls),
    path('search/', general_search, name='search_results'),
    path('courseadd/<int:id>/<int:group>/<slug:query>', joinCourse, name='join_course'),

    path('signup/', signup, name='signup'),
    path('student/<int:id>', student_view, name='student'),
    path('requestedCourses/<int:id>', student_requested_courses_view, name='requestedCourses'),
    path('professor/<int:id>', professor_view, name='professor'),
    path('notifications/<int:id>', professor_notifications, name='professor_notifications'),
    path('verify/<int:cid>/<int:gid>/<int:sid>', prof_add_student, name='add_student'),
    path('reject/<int:cid>/<int:gid>/<int:sid>', prof_reject_student, name='add_student'),
    path('verify_all/', verify_all, name='add_student'),

    path('archiveCourseProfessor/<int:id>', archiveCourseProfessor_view, name='ArchivedCourseProfessor'),
    path('professorDeleteCourse/<int:cid>/<int:gid>', professorDeleteCourse_view, name='professorDeleteCourse'),
    path('professorArchiveCourse/<int:cid>/<int:gid>', professorArchiveCourse_view, name='professorArchiveCourse'),
    path('StudentCourseList/<int:cid>/<int:gid>', StudentCourseList_view, name='StudentCourseList'),
    path('archiveCourseStudent/<int:id>', archiveCourseStudent_view, name='ArchivedCourseStudent'),

    path('CourseForm/<int:id>', AddCourse, name='addcourseform'),
    path('Course/<int:cid>/<int:gid>', courseHome,name="courseHome"),

    path('Verification/<int:id>', verification, name='verification'),

    path('Course/<int:cid>/<int:gid>/AddMultChoiceQ', AddMultipleChoiceQuestion, name='MultChoiceQ'),

    path('Course/<int:cid>/<int:gid>/AddLongAnswerQ', AddLongAnswerQuestion, name='LongAnswerQ'),

    path('QuestionSearch/<int:cid>/<int:gid>', question_search),

    path('QuestionSearchStudent/<int:cid>/<int:gid>', question_search_student),



    path('Course/<int:cid>/<int:gid>/Question/<int:qid>', question_view_general, name='general_question'),
    url(r'^logout/$', user_logout, name='logout')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Course/models.py
from django.db import models
from Professor.models import Professor
from Student.models import Student as St
from Question.models import Question
# Create your models here.

StatusChoices = [('active', 'active'), ('archived', 'archived')]
class Course(models.Model):
    CourseID = models.PositiveIntegerField(null=False, blank=False)
    GroupID = models.PositiveSmallIntegerField(null=False, blank=False)
    Name = models.CharField(null=False, blank=False, max_length=100)
    Professor = models.ManyToManyField(Professor, blank=False)
    Student = models.ManyToManyField(St, blank=False)
    not_verified_students = models.ManyToManyField(St, blank=False, related_name='not_verified')
    Questions = models.ManyToManyField(Question,  blank=True)
    Status = models.CharField(max_length=20, null=True, blank=False, choices=StatusChoices, default='active')

    class Meta:
        ordering = ['CourseID']
        unique_together = (('CourseID', 'GroupID'),)

templates/VerificationPage.html
{% load static %}


<head>
  <meta charset="UTF-8">
  <title>Welcome</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes"><link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'><link rel="stylesheet" href="{% static "css/style.css"%}">

</head>
<body>
<!-- partial:index.partial.html -->
<div class="cont">
  <div class="demo">
    <div class="login">

      <div class="login__check"></div>
<form action="/Verification/{{id}}" method="post", enctype="multipart/form-data">
      <div class="login__form">

        <div class="login__row">
          
          <svg class="login__icon name svg-icon" viewBox="0 0 20 20">
            <path d="M0,20 a10,8 0 0,1 20,0z M10,0 a4,4 0 0,1 0,8 a4,4 0 0,1 0,-8" />
          </svg>
          
          <input name="verify" id="dehghoon" type="text" class="login__input name" placeholder="Please enter verification code"/>
        </div>
        <button type="submit" class="login__submit">Submit</button>
        
      </div>
      
    </div>
    </form>
    <div class="app">
      <div class="app__top">
        <div class="app__menu-btn">
          <span></span>
        </div>
        <svg class="app__icon search svg-icon" viewBox="0 0 20 20">
          <!-- yeap, its purely hardcoded numbers straight from the head :D (same for svg above) -->
          <path d="M20,20 15.36,15.36 a9,9 0 0,1 -12.72,-12.72 a 9,9 0 0,1 12.72,12.72" />
        </svg>
        <p class="app__hello">Good Morning!</p>
        <div class="app__user">
          <img src="{% static "images/Sharif.jpg" %}" alt="" class="app__user-photo" />
          <span class="app__user-notif">3</span>
        </div>
        <div class="app__month">
          <span class="app__month-btn left"></span>
          <p class="app__month-name">March</p>
          <span class="app__month-btn right"></span>
        </div>
      </div>
      <div class="app__bot">
        <div class="app__days">
          <div class="app__day weekday">Sun</div>
          <div class="app__day weekday">Mon</div>
          <div class="app__day weekday">Tue</div>
          <div class="app__day weekday">Wed</div>
          <div class="app__day weekday">Thu</div>
          <div class="app__day weekday">Fri</div>
          <div class="app__day weekday">Sad</div>
          <div class="app__day date">8</div>
          <div class="app__day date">9</div>
          <div class="app__day date">10</div>
          <div class="app__day date">11</div>
          <div class="app__day date">12</div>
          <div class="app__day date">13</div>
          <div class="app__day date">14</div>
        </div>
        <div class="app__meetings">
          <div class="app__meeting">
            <img src="{% static "images/Sharif.jpg" %}" alt="" class="app__meeting-photo" />
            <p class="app__meeting-name">Feed the cat</p>
            <p class="app__meeting-info">
              <span class="app__meeting-time">8 - 10am</span>
              <span class="app__meeting-place">Real-life</span>
            </p>
          </div>
          <div class="app__meeting">
            <img src="{% static "images/Sharif.jpg" %}" alt="" class="app__meeting-photo" />
            <p class="app__meeting-name">Feed the cat!</p>
            <p class="app__meeting-info">
              <span class="app__meeting-time">1 - 3pm</span>
              <span class="app__meeting-place">Real-life</span>
            </p>
          </div>
          <div class="app__meeting">
            <img src="{% static "images/Sharif.jpg" %}" alt="" class="app__meeting-photo" />
            <p class="app__meeting-name">FEED THIS CAT ALREADY!!!</p>
            <p class="app__meeting-info">
              <span class="app__meeting-time">This button is just for demo ></span>
            </p>
          </div>
        </div>
      </div>
      <div class="app__logout">
        <svg class="app__logout-icon svg-icon" viewBox="0 0 20 20">
          <path d="M6,3 a8,8 0 1,0 8,0 M10,0 10,12"/>
        </svg>
      </div>
    </div>
  </div>
</div>
<!-- partial -->

</body>

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

{% load static %}


<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Dashboard 3</title>

    <!-- Fontfaces CSS-->
    <link href="{% static "css/font-face.css" rel="stylesheet"%}" media="all">
    <link href="{% static "vendor/font-awesome-4.7/css/font-awesome.min.css"%}" rel="stylesheet" media="all">
    <link href= "{% static "vendor/font-awesome-5/css/fontawesome-all.min.css"%}" rel="stylesheet" media="all">
    <link href= "{% static "vendor/mdi-font/css/material-design-iconic-font.min.css"%}" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href= "{% static "vendor/bootstrap-4.1/bootstrap.min.css"%}" rel="stylesheet" media="all">

    <!-- Vendor CSS-->

    <link href="{% static "vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css"%}" rel="stylesheet" media="all">
    <link href="{% static "vendor/wow/animate.css"%}" rel="stylesheet" media="all">
    <link href="{% static "vendor/css-hamburgers/hamburgers.min.css"%}" rel="stylesheet" media="all">
    <link href="{% static "vendor/slick/slick.css"%}" rel="stylesheet" media="all">
    <link href="{% static "vendor/select2/select2.min.css"%}" rel="stylesheet" media="all">
    <link href="{% static "vendor/perfect-scrollbar/perfect-scrollbar.css"%}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static "css/theme.css"%}" rel="stylesheet" media="all">

</head>

<body class="animsition">
    <div class="page-wrapper">
        <!-- HEADER DESKTOP-->
        <header class="header-desktop3 d-none d-lg-block">
            <div class="section__content section__content--p35">
                <div class="header3-wrap">
                    <div class="header__logo">
                        <a href="#">
                            <img src="{% static "images/icon/logo-white.png"%}" alt="CoolAdmin" />
                        </a>
                    </div>

                    <div class="header__tool">

                        <div class="account-wrap">
                            <div class="account-item account-item--style2 clearfix js-item-menu">
                                <div class="image">
                                   <img src="{{object.profile_pic.url}}" alt="Avatar" />
                                </div>
                                <div class="content">
                                    <a class="js-acc-btn" href="#">{{ object.FirstName }} {{object.LastName }} </a>
                                </div>
                                <div class="account-dropdown js-dropdown">
                                    <div class="info clearfix">
                                        <div class="image">
                                            <a href="#">
                                                <img src="{{object.profile_pic.url}}" alt="" />
                                            </a>
                                        </div>
                                        <div class="content">
                                            <h5 class="name">
                                                <a href="">{{ object.FirstName }} {{object.LastName }}</a>
                                            </h5>
                                            <span class="email">{{object}}</span>
                                        </div>
                                    </div>
                                    <div class="account-dropdown__body">
                                        <div class="account-dropdown__item">
                                            <a href="">
                                                <i class="zmdi zmdi-account"></i>Account</a>
                                        </div>
                                        <div class="account-dropdown__item">
                                            <a href="#">
                                                <i class="zmdi zmdi-settings"></i>Setting</a>
                                        </div>

                                    </div>
                                    <div class="account-dropdown__footer">
                                        <a href={% url 'logout' %}>
                                            <i class="zmdi zmdi-power"></i>Logout</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- END HEADER DESKTOP-->


        <!-- PAGE CONTENT-->
        <div class="page-content--bgf7">

            <!-- WELCOME-->

            <!-- END WELCOME-->

            <!-- STATISTIC-->

            <!-- END STATISTIC-->



            <!-- DATA TABLE-->

            <!-- END DATA TABLE-->


        </div>

    </div>

    <!-- Jquery JS-->
    <script src="{% static "vendor/jquery-3.2.1.min.js"%}"></script>
    <!-- Bootstrap JS-->
    <script src="{% static "vendor/bootstrap-4.1/popper.min.js"%}"></script>
    <script src="{% static "vendor/bootstrap-4.1/bootstrap.min.js"%}"></script>
    <!-- Vendor JS       -->
    <script src="{% static "vendor/slick/slick.min.js"%}">
    </script>
    <script src="{% static "vendor/wow/wow.min.js"%}"></script>
    <script src="{% static "vendor/animsition/animsition.min.js"%}"></script>
    <script src="{% static "vendor/bootstrap-progressbar/bootstrap-progressbar.min.js"%}">
    </script>
    <script src="{% static "vendor/counter-up/jquery.waypoints.min.js"%}"></script>
    <script src="{% static "vendor/counter-up/jquery.counterup.min.js"%}">
    </script>
    <script src="{% static "vendor/circle-progress/circle-progress.min.js"%}"></script>
    <script src="{% static "vendor/perfect-scrollbar/perfect-scrollbar.js"%}"></script>
    <script src="{% static "vendor/chartjs/Chart.bundle.min.js"%}"></script>
    <script src="{% static "vendor/select2/select2.min.js"%}">
    </script>

    <!-- Main JS-->


    <script src="{% static "js/main.js "%}"></script>

</body>

</html>
<!-- end document-->

{% block content %}

{% endblock %}

templates/index.html
{% load static %}


<head>
  <meta charset="UTF-8">
  <title>Welcome</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes"><link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'><link rel="stylesheet" href="{% static "css/style.css"%}">

</head>
<body>
<!-- partial:index.partial.html -->
<div class="cont">
  <div class="demo">
    <div class="login">
      <div class="login__check"></div>
      <div class="login__form">
        <div class="login__row">
          <svg class="login__icon name svg-icon" viewBox="0 0 20 20">
            <path d="M0,20 a10,8 0 0,1 20,0z M10,0 a4,4 0 0,1 0,8 a4,4 0 0,1 0,-8" />
          </svg>
          <input id="dehghoon" type="text" class="login__input name" placeholder="Username"/>
        </div>
        <div class="login__row">
          <svg class="login__icon pass svg-icon" viewBox="0 0 20 20">
            <path d="M0,20 20,20 20,8 0,8z M10,13 10,16z M4,8 a6,8 0 0,1 12,0" />
          </svg>
          <input id="amrez" type="password" class="login__input pass" placeholder="Password"/>
        </div>
        <button type="button" class="login__submit">Sign in</button>
        <p class="login__signup">Don't have an account? &nbsp;<a href="signup">Sign up</a></p>
      </div>
    </div>
    <div class="app">
      <div class="app__top">
        <div class="app__menu-btn">
          <span></span>
        </div>
        <svg class="app__icon search svg-icon" viewBox="0 0 20 20">
          <!-- yeap, its purely hardcoded numbers straight from the head :D (same for svg above) -->
          <path d="M20,20 15.36,15.36 a9,9 0 0,1 -12.72,-12.72 a 9,9 0 0,1 12.72,12.72" />
        </svg>
        <p class="app__hello">Good Morning!</p>
        <div class="app__user">
          <img src="{% static "images/Sharif.jpg" %}" alt="" class="app__user-photo" />
          <span class="app__user-notif">3</span>
        </div>
        <div class="app__month">
          <span class="app__month-btn left"></span>
          <p class="app__month-name">March</p>
          <span class="app__month-btn right"></span>
        </div>
      </div>
      <div class="app__bot">
        <div class="app__days">
          <div class="app__day weekday">Sun</div>
          <div class="app__day weekday">Mon</div>
          <div class="app__day weekday">Tue</div>
          <div class="app__day weekday">Wed</div>
          <div class="app__day weekday">Thu</div>
          <div class="app__day weekday">Fri</div>
          <div class="app__day weekday">Sad</div>
          <div class="app__day date">8</div>
          <div class="app__day date">9</div>
          <div class="app__day date">10</div>
          <div class="app__day date">11</div>
          <div class="app__day date">12</div>
          <div class="app__day date">13</div>
          <div class="app__day date">14</div>
        </div>
        <div class="app__meetings">
          <div class="app__meeting">
            <img src="{% static "images/Sharif.jpg" %}" alt="" class="app__meeting-photo" />
            <p class="app__meeting-name">Feed the cat</p>
            <p class="app__meeting-info">
              <span class="app__meeting-time">8 - 10am</span>
              <span class="app__meeting-place">Real-life</span>
            </p>
          </div>
          <div class="app__meeting">
            <img src="{% static "images/Sharif.jpg" %}" alt="" class="app__meeting-photo" />
            <p class="app__meeting-name">Feed the cat!</p>
            <p class="app__meeting-info">
              <span class="app__meeting-time">1 - 3pm</span>
              <span class="app__meeting-place">Real-life</span>
            </p>
          </div>
          <div class="app__meeting">
            <img src="{% static "images/Sharif.jpg" %}" alt="" class="app__meeting-photo" />
            <p class="app__meeting-name">FEED THIS CAT ALREADY!!!</p>
            <p class="app__meeting-info">
              <span class="app__meeting-time">This button is just for demo ></span>
            </p>
          </div>
        </div>
      </div>
      <div class="app__logout">
        <svg class="app__logout-icon svg-icon" viewBox="0 0 20 20">
          <path d="M6,3 a8,8 0 1,0 8,0 M10,0 10,12"/>
        </svg>
      </div>
    </div>
  </div>
</div>
<!-- partial -->
  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script><script  src="{% static "js/script.js" %}"></script>

</body>

templates/signup.html
{% load static %}


<head>
  <meta charset="UTF-8">
  <title>Sign-Up/Login Form</title>
  <link href='https://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/css'><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
<link rel="stylesheet" href="{% static "css/signup.css"%}">

</head>
<body>
<!-- partial:index.partial.html -->
<div class="cont">
<div class="form">

      <ul class="tab-group">
        <li class="tab active"><a href="#Student">As a Student</a></li>
        <li class="tab"><a href="#Professor">As a Professor</a></li>
      </ul>
      
      <div class="tab-content">
        <div id="Student">
          <h1>Sign Up for Free</h1>
          
          <form action="/signup/" enctype="multipart/form-data" method="post">
          


          <div class="field-wrap">
              {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}

          </div>
          

          
          <button type="submit" class="button button-block"/>Get Started</button>
          
          </form>

        </div>

                  <div id="Professor">
          <h1>Sign Up for Free</h1>

          <form action="/signup/" enctype="multipart/form-data" method="post">



          <div class="field-wrap">
              {% csrf_token %}
          {{ user_form.as_p }}
          {{ prof_form.as_p }}

          </div>



          <button type="submit" class="button button-block"/>Get Started</button>

          </form>



        </div>

        
      </div><!-- tab-content -->
      </div>
</div> <!-- /form -->
<!-- partial -->
  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script><script  src="{% static "js/signup.js"%}"></script>

</body>

templates/test.html
'<li><label for="id_CourseID">CourseID:</label> <input type="number" name="CourseID" min="0" required id="id_CourseID"></li>\n<li><label for="id_GroupID">GroupID:</label> <input type="number" name="GroupID" min="0" required id="id_GroupID"></li>\n<li><label for="id_Name">Name:</label> <input type="text" name="Name" maxlength="100" required id="id_Name"></li>\n<li><label for="id_Professor">Professor:</label> <select name="Professor" required id="id_Professor" multiple>\n  <option value="2">95105050</option>\n\n</select></li>'